apiVersion: v1
kind: Service
metadata:
  name: svc-v1-local-file-server
spec:
  type: NodePort
  selector:
    app: v1-local-file-server
  ports:
  - port: 80
    # targetPort: 80 
    nodePort: 30002
