apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-test
spec:
  replicas: 1
  template:
    metadata:
      name: logger-test
      labels:
        app: logger-test
    spec:
      containers:
        - name: logger-test-container
          image: logger-test:1
          ports:
            - containerPort: 80
          resources:
#            requests:
#              cpu: 20m
            requests:
              cpu: 300m
              memory: 2048M
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 60
            failureThreshold: 5
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 20
            failureThreshold: 5
            initialDelaySeconds: 30
  selector:
    matchLabels:
      app: logger-test
