apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-test
spec:
  replicas: 3
  template:
    metadata:
      name: logger-test
      labels:
        app: logger-test
    spec:
      containers:
        - name: logger-test-container
          image: logger-test:1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: logger-test
