apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  selector:
    app: v1-portal-noticias
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  externalIPs:
    - "192.168.2.201"
